# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"setup_training_data_for_labeling": "1_setup_training_images.ipynb",
         "app": "1_setup_training_images.ipynb"}

modules = ["setup_images.py"]

doc_url = "https://sizhky.github.io/auto_train/"

git_url = "https://github.com/sizhky/auto_train/tree/master/"

def custom_doc_links(name): return None
