# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/1_setup_training_images.ipynb (unless otherwise specified).

__all__ = ['setup_training_data_for_labeling', 'app']

# Cell
from torch_snippets import *
from torch_snippets.registry import *
import typer

app = typer.Typer()

@app.command()
def setup_training_data_for_labeling(config_path, label_studio_dump):
    config = AttrDict(Config().from_disk(config_path))
    df = pd.read_csv(label_studio_dump)
    np.random.seed(42)
    df['split'] = np.random.choice(
        ['train_dir', 'validation_dir'],
        size=len(df), replace=True,
        p=[config.training.train_ratio, 1-config.training.train_ratio]
    )

    for ix, row in df.iterrows():
        row = row.squeeze()
        _from = P(row.image.replace('/data', config.label_studio.base_data_dir+'/media/'))
        _to = P(config.training.data[row.split])/fname(_from)
        makedir(_to.parent)
        print(f'{str(_from):50} --> {str(_to):>50} {" ":20} {(1+ix)/len(df)*100:.2f}%')
        _from.cp(_to)

if __name__ == '__main__':
    app()